name: Deploy Flask Service to ECS
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: main

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        run: |
          IMAGE="$637675605421.dkr.ecr.us-east-1.amazonaws.com/my-flask-app:latest"
          docker build -t $IMAGE ./flask-app
          docker push $IMAGE

      - name: Fetch Current ECS Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition flask-task \
            --region us-east-1 > task-definition.json

      - name: Update ECS Task Definition with New Image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/my-flask-app:latest"
          jq --arg IMAGE "$IMAGE_URI" '.taskDefinition.containerDefinitions[0].image = $IMAGE' task-definition.json \
          | jq '.taskDefinition | {family, containerDefinitions, executionRoleArn, taskRoleArn, networkMode, requiresCompatibilities, cpu, memory}' \
          > new-task-def.json

      - name: Register New ECS Task Definition
        run: |
          aws ecs register-task-definition --cli-input-json file://new-task-def.json > register-task-def-out.json
          TASK_REVISION=$(jq -r '.taskDefinition.revision' register-task-def-out.json)
          echo "TASK_REVISION=$TASK_REVISION" >> $GITHUB_ENV

      - name: Deploy to ECS Service
        run: |
          aws ecs update-service \
            --cluster flask-cluster1 \
            --service flask-task-service-ee55ylp4 \
            --task-definition flask-task:$TASK_REVISION \
            --region us-east-1
